avatar:
  img: /img/avatar.png
  effect: true
subtitle:
  enable: true
  text1: 欢迎来到我的博客
  text2: 记录生活与技术
preloader:
  enable: false
background:
  enable: true
  image: https://s41.ax1x.com/2026/04/05/petfh1f.png
